In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Social_Network_Ads.csv')

In [5]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
df=df.iloc[:,2:]

In [9]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('Purchased',axis=1),df['Purchased'],test_size=0.3,random_state=0)

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [17]:
x_train_scaled

array([[0.19047619, 0.        ],
       [1.        , 0.64444444],
       [0.47619048, 0.71851852],
       [0.52380952, 0.68148148],
       [0.57142857, 0.28148148],
       [0.4047619 , 0.32592593],
       [0.71428571, 0.19259259],
       [0.71428571, 0.88148148],
       [0.47619048, 0.72592593],
       [0.26190476, 0.98518519],
       [0.19047619, 0.        ],
       [1.        , 0.2       ],
       [0.14285714, 0.02962963],
       [0.57142857, 0.99259259],
       [0.66666667, 0.6       ],
       [0.23809524, 0.32592593],
       [0.5       , 0.6       ],
       [0.23809524, 0.54814815],
       [0.54761905, 0.42222222],
       [0.64285714, 0.08148148],
       [0.35714286, 0.4       ],
       [0.04761905, 0.4962963 ],
       [0.30952381, 0.43703704],
       [0.57142857, 0.48148148],
       [0.4047619 , 0.42222222],
       [0.35714286, 0.99259259],
       [0.52380952, 0.41481481],
       [0.78571429, 0.97037037],
       [0.66666667, 0.47407407],
       [0.4047619 , 0.44444444],
       [0.47619048, 0.26666667],
       [0.42857143, 0.44444444],
       [0.45238095, 0.46666667],
       [0.47619048, 0.34074074],
       [1.        , 0.68888889],
       [0.04761905, 0.4962963 ],
       [0.92857143, 0.43703704],
       [0.57142857, 0.37037037],
       [0.19047619, 0.48148148],
       [0.66666667, 0.75555556],
       [0.4047619 , 0.34074074],
       [0.07142857, 0.39259259],
       [0.23809524, 0.21481481],
       [0.54761905, 0.53333333],
       [0.45238095, 0.13333333],
       [0.21428571, 0.55555556],
       [0.5       , 0.2       ],
       [0.23809524, 0.8       ],
       [0.30952381, 0.76296296],
       [0.16666667, 0.53333333],
       [0.4047619 , 0.41481481],
       [0.45238095, 0.40740741],
       [0.4047619 , 0.17777778],
       [0.69047619, 0.05925926],
       [0.4047619 , 0.97777778],
       [0.71428571, 0.91111111],
       [0.19047619, 0.52592593],
       [0.16666667, 0.47407407],
       [0.80952381, 0.91111111],
       [0.78571429, 0.05925926],
       [0.4047619 , 0.33333333],
       [0.35714286, 0.72592593],
       [0.28571429, 0.68148148],
       [0.71428571, 0.13333333],
       [0.54761905, 0.48148148],
       [0.71428571, 0.6       ],
       [0.30952381, 0.02222222],
       [0.30952381, 0.41481481],
       [0.5952381 , 0.84444444],
       [0.97619048, 0.45185185],
       [0.        , 0.21481481],
       [0.42857143, 0.76296296],
       [0.57142857, 0.55555556],
       [0.69047619, 0.11111111],
       [0.19047619, 0.20740741],
       [0.52380952, 0.46666667],
       [0.66666667, 0.32592593],
       [0.97619048, 0.2       ],
       [0.66666667, 0.43703704],
       [0.4047619 , 0.56296296],
       [0.23809524, 0.32592593],
       [0.52380952, 0.31111111],
       [0.97619048, 0.94814815],
       [0.92857143, 0.08148148],
       [0.80952381, 0.17037037],
       [0.69047619, 0.72592593],
       [0.83333333, 0.94814815],
       [0.4047619 , 0.08888889],
       [0.95238095, 0.63703704],
       [0.64285714, 0.22222222],
       [0.11904762, 0.4962963 ],
       [0.66666667, 0.05925926],
       [0.57142857, 0.37037037],
       [0.23809524, 0.51111111],
       [0.47619048, 0.32592593],
       [0.19047619, 0.51111111],
       [0.26190476, 0.0962963 ],
       [0.45238095, 0.41481481],
       [0.0952381 , 0.2962963 ],
       [0.71428571, 0.14814815],
       [0.73809524, 0.0962963 ],
       [0.47619048, 0.37037037],
       [0.21428571, 0.01481481],
       [0.66666667, 0.0962963 ],
       [0.71428571, 0.93333333],
       [0.19047619, 0.01481481],
       [0.4047619 , 0.60740741],
       [0.5       , 0.32592593],
       [0.14285714, 0.08888889],
       [0.33333333, 0.02222222],
       [0.66666667, 0.54074074],
       [0.4047619 , 0.31851852],
       [0.9047619 , 0.33333333],
       [0.69047619, 0.14074074],
       [0.52380952, 0.42222222],
       [0.33333333, 0.62962963],
       [0.02380952, 0.04444444],
       [0.16666667, 0.55555556],
       [0.4047619 , 0.54074074],
       [0.23809524, 0.12592593],
       [0.76190476, 0.03703704],
       [0.52380952, 0.32592593],
       [0.76190476, 0.21481481],
       [0.4047619 , 0.42222222],
       [0.52380952, 0.94074074],
       [0.66666667, 0.12592593],
       [0.5       , 0.41481481],
       [0.04761905, 0.43703704],
       [0.26190476, 0.44444444],
       [0.30952381, 0.45185185],
       [0.69047619, 0.07407407],
       [0.52380952, 0.34074074],
       [0.38095238, 0.71851852],
       [0.47619048, 0.48148148],
       [0.57142857, 0.44444444],
       [0.69047619, 0.23703704],
       [0.5       , 0.44444444],
       [0.02380952, 0.07407407],
       [0.45238095, 0.48148148],
       [0.42857143, 0.33333333],
       [0.54761905, 0.27407407],
       [0.42857143, 0.81481481],
       [0.71428571, 0.1037037 ],
       [0.42857143, 0.82222222],
       [0.78571429, 0.88148148],
       [0.21428571, 0.31111111],
       [0.47619048, 0.41481481],
       [0.5       , 0.34074074],
       [0.0952381 , 0.08888889],
       [0.35714286, 0.33333333],
       [0.71428571, 0.43703704],
       [0.95238095, 0.05925926],
       [0.83333333, 0.42222222],
       [0.33333333, 0.75555556],
       [0.85714286, 0.40740741],
       [0.28571429, 0.48148148],
       [0.95238095, 0.59259259],
       [0.19047619, 0.27407407],
       [0.64285714, 0.47407407],
       [0.14285714, 0.2962963 ],
       [0.52380952, 0.44444444],
       [0.35714286, 0.0962963 ],
       [0.61904762, 0.91851852],
       [0.0952381 , 0.02222222],
       [0.35714286, 0.26666667],
       [0.5952381 , 0.87407407],
       [0.14285714, 0.12592593],
       [0.66666667, 0.05185185],
       [0.4047619 , 0.2962963 ],
       [0.85714286, 0.65925926],
       [0.71428571, 0.77037037],
       [0.4047619 , 0.28148148],
       [0.45238095, 0.95555556],
       [0.11904762, 0.37777778],
       [0.45238095, 0.9037037 ],
       [0.30952381, 0.31851852],
       [0.35714286, 0.19259259],
       [0.64285714, 0.05185185],
       [0.28571429, 0.        ],
       [0.02380952, 0.02962963],
       [0.73809524, 0.43703704],
       [0.5       , 0.79259259],
       [0.4047619 , 0.42962963],
       [0.5       , 0.41481481],
       [0.14285714, 0.05925926],
       [0.54761905, 0.42222222],
       [0.26190476, 0.5037037 ],
       [0.85714286, 0.08148148],
       [0.4047619 , 0.21481481],
       [0.45238095, 0.44444444],
       [0.26190476, 0.23703704],
       [0.30952381, 0.39259259],
       [0.57142857, 0.28888889],
       [0.28571429, 0.88888889],
       [0.80952381, 0.73333333],
       [0.76190476, 0.15555556],
       [0.9047619 , 0.87407407],
       [0.26190476, 0.34074074],
       [0.28571429, 0.54814815],
       [0.19047619, 0.00740741],
       [0.35714286, 0.11851852],
       [0.54761905, 0.42222222],
       [0.42857143, 0.13333333],
       [0.88095238, 0.81481481],
       [0.71428571, 0.85925926],
       [0.54761905, 0.41481481],
       [0.28571429, 0.34814815],
       [0.45238095, 0.42222222],
       [0.54761905, 0.35555556],
       [0.95238095, 0.23703704],
       [0.28571429, 0.74814815],
       [0.04761905, 0.25185185],
       [0.45238095, 0.43703704],
       [0.54761905, 0.32592593],
       [0.73809524, 0.54814815],
       [0.23809524, 0.47407407],
       [0.83333333, 0.4962963 ],
       [0.52380952, 0.31111111],
       [1.        , 0.14074074],
       [0.4047619 , 0.68888889],
       [0.07142857, 0.42222222],
       [0.47619048, 0.41481481],
       [0.5       , 0.67407407],
       [0.45238095, 0.31111111],
       [0.19047619, 0.42222222],
       [0.4047619 , 0.05925926],
       [0.85714286, 0.68888889],
       [0.28571429, 0.01481481],
       [0.5       , 0.88148148],
       [0.26190476, 0.20740741],
       [0.35714286, 0.20740741],
       [0.4047619 , 0.17037037],
       [0.54761905, 0.22222222],
       [0.54761905, 0.42222222],
       [0.5       , 0.88148148],
       [0.21428571, 0.9037037 ],
       [0.07142857, 0.00740741],
       [0.19047619, 0.12592593],
       [0.30952381, 0.37777778],
       [0.5       , 0.42962963],
       [0.54761905, 0.47407407],
       [0.69047619, 0.25925926],
       [0.54761905, 0.11111111],
       [0.45238095, 0.57777778],
       [1.        , 0.22962963],
       [0.16666667, 0.05185185],
       [0.23809524, 0.16296296],
       [0.47619048, 0.2962963 ],
       [0.42857143, 0.28888889],
       [0.04761905, 0.15555556],
       [0.9047619 , 0.65925926],
       [0.52380952, 0.31111111],
       [0.57142857, 0.68888889],
       [0.04761905, 0.05925926],
       [0.52380952, 0.37037037],
       [0.69047619, 0.03703704],
       [0.        , 0.52592593],
       [0.4047619 , 0.47407407],
       [0.92857143, 0.13333333],
       [0.38095238, 0.42222222],
       [0.73809524, 0.17777778],
       [0.21428571, 0.11851852],
       [0.02380952, 0.40740741],
       [0.5       , 0.47407407],
       [0.19047619, 0.48888889],
       [0.16666667, 0.48148148],
       [0.23809524, 0.51851852],
       [0.88095238, 0.17777778],
       [0.76190476, 0.54074074],
       [0.73809524, 0.54074074],
       [0.80952381, 1.        ],
       [0.4047619 , 0.37037037],
       [0.57142857, 0.28888889],
       [0.38095238, 0.20740741],
       [0.45238095, 0.27407407],
       [0.71428571, 0.11111111],
       [0.26190476, 0.20740741],
       [0.42857143, 0.27407407],
       [0.21428571, 0.28888889],
       [0.19047619, 0.76296296]])

In [19]:
x_test_scaled

array([[0.28571429, 0.53333333],
       [0.47619048, 0.25925926],
       [0.4047619 , 0.44444444],
       [0.28571429, 0.47407407],
       [0.4047619 , 0.25925926],
       [0.21428571, 0.03703704],
       [0.30952381, 0.        ],
       [0.42857143, 0.95555556],
       [0.        , 0.39259259],
       [0.69047619, 0.20740741],
       [0.28571429, 0.25185185],
       [0.23809524, 0.2962963 ],
       [0.45238095, 0.2962963 ],
       [0.5       , 0.45925926],
       [0.04761905, 0.52592593],
       [0.33333333, 0.75555556],
       [0.45238095, 0.45925926],
       [0.02380952, 0.51851852],
       [0.88095238, 0.85185185],
       [0.4047619 , 0.05185185],
       [0.4047619 , 0.23703704],
       [0.69047619, 0.95555556],
       [0.54761905, 0.26666667],
       [0.69047619, 0.66666667],
       [0.11904762, 0.0962963 ],
       [0.73809524, 0.93333333],
       [0.23809524, 0.53333333],
       [0.26190476, 0.48148148],
       [0.45238095, 0.34814815],
       [0.33333333, 0.52592593],
       [0.07142857, 0.54074074],
       [0.45238095, 0.47407407],
       [0.92857143, 0.33333333],
       [0.45238095, 0.28148148],
       [0.14285714, 0.31851852],
       [0.        , 0.27407407],
       [0.0952381 , 0.48888889],
       [0.38095238, 0.20740741],
       [0.30952381, 0.14074074],
       [0.73809524, 0.15555556],
       [0.21428571, 0.54074074],
       [0.54761905, 0.27407407],
       [0.21428571, 0.51111111],
       [0.4047619 , 0.03703704],
       [0.5952381 , 0.71851852],
       [0.21428571, 0.31851852],
       [0.45238095, 0.48148148],
       [0.80952381, 0.55555556],
       [0.19047619, 0.11111111],
       [0.73809524, 0.52592593],
       [0.92857143, 0.79259259],
       [0.38095238, 0.07407407],
       [0.4047619 , 0.31111111],
       [0.38095238, 0.74074074],
       [0.97619048, 0.54074074],
       [0.64285714, 0.12592593],
       [0.26190476, 0.5037037 ],
       [0.19047619, 0.48148148],
       [0.73809524, 0.0962963 ],
       [0.11904762, 0.03703704],
       [0.33333333, 0.02222222],
       [1.        , 0.2       ],
       [0.02380952, 0.45185185],
       [0.42857143, 0.62222222],
       [0.02380952, 0.08148148],
       [1.        , 0.5037037 ],
       [0.14285714, 0.54814815],
       [0.21428571, 0.31851852],
       [0.52380952, 0.23703704],
       [0.57142857, 0.40740741],
       [0.33333333, 1.        ],
       [0.4047619 , 0.45925926],
       [0.0952381 , 0.35555556],
       [0.64285714, 0.05185185],
       [0.21428571, 0.54814815],
       [0.        , 0.4962963 ],
       [0.57142857, 0.47407407],
       [0.52380952, 0.33333333],
       [0.83333333, 0.14074074],
       [0.69047619, 0.68148148],
       [0.95238095, 0.95555556],
       [0.97619048, 0.5037037 ],
       [0.14285714, 0.2962963 ],
       [0.19047619, 0.14814815],
       [0.95238095, 0.17037037],
       [0.57142857, 0.48148148],
       [0.52380952, 0.44444444],
       [0.97619048, 0.85185185],
       [0.66666667, 0.19259259],
       [0.54761905, 0.33333333],
       [0.57142857, 0.36296296],
       [0.45238095, 0.97037037],
       [0.11904762, 0.24444444],
       [0.16666667, 0.13333333],
       [0.14285714, 0.51111111],
       [0.21428571, 0.6       ],
       [0.11904762, 0.35555556],
       [0.71428571, 0.13333333],
       [0.71428571, 0.55555556],
       [0.57142857, 0.65925926],
       [0.61904762, 0.17777778],
       [0.33333333, 0.77777778],
       [0.47619048, 0.25925926],
       [0.33333333, 0.88888889],
       [0.80952381, 0.04444444],
       [0.83333333, 0.65925926],
       [0.5       , 0.2       ],
       [0.47619048, 0.34074074],
       [0.42857143, 0.25925926],
       [0.42857143, 0.35555556],
       [0.4047619 , 0.07407407],
       [0.4047619 , 0.25925926],
       [0.57142857, 0.42962963],
       [0.69047619, 0.25185185],
       [0.97619048, 0.1037037 ],
       [0.73809524, 0.37037037],
       [0.64285714, 0.85925926],
       [0.30952381, 0.54814815],
       [0.66666667, 0.4962963 ],
       [0.69047619, 0.26666667]])

In [21]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled=pd.DataFrame(x_test_scaled,columns=x_test.columns)

In [23]:
x_train_scaled

          Age  EstimatedSalary
0    0.190476         0.000000
1    1.000000         0.644444
2    0.476190         0.718519
3    0.523810         0.681481
4    0.571429         0.281481
..        ...              ...
275  0.714286         0.111111
276  0.261905         0.207407
277  0.428571         0.274074
278  0.214286         0.288889
279  0.190476         0.762963

[280 rows x 2 columns]

In [25]:
x_test_scaled

          Age  EstimatedSalary
0    0.285714         0.533333
1    0.476190         0.259259
2    0.404762         0.444444
3    0.285714         0.474074
4    0.404762         0.259259
..        ...              ...
115  0.738095         0.370370
116  0.642857         0.859259
117  0.309524         0.548148
118  0.666667         0.496296
119  0.690476         0.266667

[120 rows x 2 columns]

In [27]:
np.round(x_train_scaled.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean     0.5              0.4
std      0.2              0.3
min      0.0              0.0
25%      0.3              0.2
50%      0.5              0.4
75%      0.7              0.5
max      1.0              1.0